### ISSUE TITLE
Question: Send & Recieve?

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-os#20]
Switch between userspace ang kernel is provided by
Solution 1:
 **calling function `SysCall()`.**
Solution 2:
set and lock global processor context that will be managed by separated kernel thread `SysCall()`

**Comment by buzzcz** [comment]
Typical implementations are:

- Many-to-one model: All system calls from any user thread in a process are handled by a single kernel-level thread. This model has a serious drawback – any blocking system call (like awaiting input from user) can freeze all the other threads. Also, since only one thread can access the kernel at a time, this model cannot utilize multiple cores of processor.
- One-to-one model: Every user thread gets attached to a distinct kernel-level thread during a system call. This model solves the above problem of blocking system calls. It is found in all major distribution of Linux, recent Windows and Solaris versions.
- Many-to-many model: In this model a pool of user threads is mapped to a pool of kernel threads. All system calls from a user thread pool are handled by the threads in their corresponding kernel thread pool
- Hybrid model: This model implements both many to many and one to one model depending upon choice made by the kernel. This is found in old versions of IRIX, HP-UX and Solaris.

I think it could either start a new thread for each syscall (seems like an overhead for us) or the same thread executes the syscall.

**Comment by vairad** [comment]
At the moment same thread executes syscall
