### ISSUE TITLE
Stopping programs

### ISSUE THREAD

**Issue by buzzcz** [vairad/zcu-os#25]
If an error during program run occurs, should we stop all the other programs? I guess so, but how should this be done? Using syscall and Close_Handle with the process handle?

**Comment by Thoronir42** [comment]
Do we have a way to detect / handle terminal error?

Wouldn't it be enough to make sure that the streams are closed properly and have the rest of the programs in chain finish with undeterministic results?

If we have this chain
`type hi.txt ole.txt GUTEN-TAG.txt | freq > bye.txt`
we should think about what happens when:
 - type fails
   - presumably freq just reads EOF and ends without a hiccup
 - freq fails
   - type would hang on write indifinetely because of the pipe not being emptied
   - possible solution: once the read end of pipe is closed, the write is no longer blocking and instead returns an error
